### ISSUE TITLE
Tracking Problems

### ISSUE THREAD

**Issue by ZahraAnam** [ambakick/Person-Detection-and-Tracking#19]
Hi Guys! First of all Thank you for such a good implementation of People detection and tracking and making it opensource.
I am trying to run your code but have some errors in the initial loop cases, as for begining the tracking has some problems.
I tried some changes but am scared that I might mess up the code, can you please guide me a bit or change in the main Person-det-track code??

Traceback (most recent call last):
  File "Person_det_track.py", line 224, in <module>
    new_img = pipeline(img)
  File "Person_det_track.py", line 114, in pipeline
    = assign_detections_to_trackers(x_box, z_box, iou_thrd = 0.3)  
  File "Person_det_track.py", line 68, in assign_detections_to_trackers
    if (IOU_mat[m[0],m[1]]<iou_thrd):
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by ChenJiajun0011** [comment]
same problem. seems x_box is none...

**Comment by megha5965** [comment]
Is the problem solved, if yes, then how? Please let me know!!
